# These are supported funding model platforms

saweria: # Replace with up to 4 Saweria Sponsors-enabled usernames bagussatoto1 [https://saweria.co/bagussatoto1]
patreon: # Replace with a single Patreon username bagussatoto [https://www.patreon.com/]
open_collective: # Replace with a single Open Collective username bagussatoto [https://opencollective.com/]
ko_fi: # Replace with a single Ko-fi username bagussatoto [https://ko-fi.com/]
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel [https://tidelift.com/]
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry [https://communitybridge.org/]
liberapay: # Replace with a single Liberapay username bagussatoto [https://liberapay.com/]
issuehunt: # Replace with a single IssueHunt username bagussatoto [https://issuehunt.io/]
otechie: # Replace with a single Otechie username bagussatoto [https://otechie.com/]
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry [https://lfx.io/]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2'] [https://example.com/]

custom : https://www.paypal.com/paypalme/bagussatoto1
custom : https://saweria.co/bagussatoto1 
